const menuBtn=document.getElementById('menuBtn');const nav=document.getElementById('navLinks');if(menuBtn&&nav){menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const dateInput=document.getElementById('date');if(dateInput)dateInput.min=new Date().toISOString().split('T')[0];
const appointmentForm=document.getElementById('appointmentForm');if(appointmentForm){appointmentForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(appointmentForm);const consent=document.getElementById('consent');const status=document.getElementById('formStatus');if(!appointmentForm.checkValidity()||!consent?.checked){status.textContent='Please complete the required fields and consent checkbox.';appointmentForm.reportValidity();return;}const msg=`Appointment Request - Gawade Multispeciality Hospital\nPatient: ${f.get('patientName')}\nMobile: ${f.get('mobile')}\nDoctor/Department: ${f.get('doctor')}\nPreferred date: ${f.get('date')}\nPreferred time: ${f.get('time')}\nReason: ${f.get('reason')||'Not specified'}`;window.open(`https://wa.me/919766334466?text=${encodeURIComponent(msg)}`,'_blank','noopener');status.textContent='WhatsApp opened. Please review and send your request.';});}
const careerForm=document.getElementById('careerForm');if(careerForm){careerForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(careerForm);if(!careerForm.checkValidity()){careerForm.reportValidity();return;}const msg=`Career Enquiry - Gawade Multispeciality Hospital\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nEmail: ${f.get('email')}\nRole: ${f.get('role')}\nExperience: ${f.get('experience')}\nMessage: ${f.get('message')||'-'}`;window.open(`https://wa.me/919766334466?text=${encodeURIComponent(msg)}`,'_blank','noopener');});}
const serviceButtons=[...document.querySelectorAll('[data-filter]')];const serviceCards=[...document.querySelectorAll('[data-category]')];serviceButtons.forEach(btn=>btn.addEventListener('click',()=>{serviceButtons.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const filter=btn.dataset.filter;serviceCards.forEach(card=>card.hidden=filter!=='all'&&card.dataset.category!==filter)}));
const search=document.getElementById('serviceSearch');if(search){search.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();serviceCards.forEach(card=>{const categoryActive=!serviceButtons.length||serviceButtons.find(b=>b.classList.contains('active'))?.dataset.filter==='all'||serviceButtons.find(b=>b.classList.contains('active'))?.dataset.filter===card.dataset.category;card.hidden=!(categoryActive&&card.textContent.toLowerCase().includes(q));});});}


// V2 bilingual English/Marathi support. Applies to patient-facing UI and core content.
const I18N_MR = {
  'Home':'मुख्यपृष्ठ','About':'आमच्याबद्दल','About Us':'आमच्याबद्दल','Doctors':'डॉक्टर्स','Services':'सेवा','Facilities':'सुविधा','Insurance':'विमा','Contact':'संपर्क','Career':'करिअर','Privacy':'गोपनीयता',
  'Book Appointment':'अपॉइंटमेंट बुक करा','Book an Appointment':'अपॉइंटमेंट बुक करा','Appointment':'अपॉइंटमेंट','Call Hospital':'रुग्णालयाला कॉल करा','Call Now':'आता कॉल करा','WhatsApp':'व्हॉट्सअॅप','Directions':'मार्गदर्शन','Get Directions':'दिशा मिळवा','Open Google Maps':'Google Maps उघडा','Call for directions':'दिशांसाठी कॉल करा','View all doctors':'सर्व डॉक्टर पहा',
  '24×7 Emergency & Critical Care • Rajgurunagar':'२४×७ आपत्कालीन व क्रिटिकल केअर • राजगुरुनगर','Advanced multispeciality care • Rajgurunagar':'प्रगत मल्टिस्पेशालिटी सेवा • राजगुरुनगर',
  'Expert care for every stage of life, close to home.':'जीवनाच्या प्रत्येक टप्प्यासाठी तज्ज्ञ उपचार — आपल्या जवळ.',
  'Centers of Excellence':'उत्कृष्टता केंद्रे','Specialist departments, connected around the patient':'रुग्णकेंद्रित समन्वित तज्ज्ञ विभाग','Surgical Services':'शस्त्रक्रिया सेवा','Medical Department':'वैद्यकीय विभाग','Women & Children':'महिला व बाल आरोग्य','Diagnostics':'निदान सेवा','Imaging & Laboratory':'इमेजिंग व प्रयोगशाळा','Specialized Clinics':'विशेष क्लिनिक','Emergency & Trauma':'आपत्कालीन व ट्रॉमा सेवा','Preventive Care':'प्रतिबंधात्मक आरोग्य सेवा',
  'Our Doctors':'आमचे डॉक्टर','Multidisciplinary specialist team':'बहुविशेषज्ञ तज्ज्ञ टीम','Facilities':'सुविधा','Critical Care':'क्रिटिकल केअर','Operation Theaters':'ऑपरेशन थिएटर्स','24-Hour Lab':'२४ तास प्रयोगशाळा','In-House Medical Store':'रुग्णालयातील औषध दुकान',
  'Google Reviews':'Google पुनरावलोकने','View on Google Maps':'Google Maps वर पहा','Write a Google review →':'Google वर पुनरावलोकन लिहा →','Visit Us':'आम्हाला भेट द्या','Easy to find on Pabal Road, Rajgurunagar':'पाबळ रोड, राजगुरुनगर येथे सहज पोहोचा',
  'Hospital Details':'रुग्णालयाची माहिती','Address':'पत्ता','Phone':'फोन','Email':'ईमेल','Emergency':'आपत्कालीन','Need medical advice or treatment?':'वैद्यकीय सल्ला किंवा उपचारांची गरज आहे का?','Schedule a consultation with the hospital team using the appointment flow.':'अपॉइंटमेंट प्रक्रियेद्वारे रुग्णालयातील तज्ज्ञांशी सल्लामसलत ठरवा.',
  'Our Medical Team':'आमची वैद्यकीय टीम','Specialist doctors across multiple disciplines':'विविध क्षेत्रांतील तज्ज्ञ डॉक्टर','Request appointment →':'अपॉइंटमेंटची विनंती करा →','Core Values':'मूल्ये','Who We Are':'आम्ही कोण आहोत','Mission':'ध्येय','Vision':'दृष्टी',
  'Quick Links':'त्वरित दुवे','Centers of Excellence':'उत्कृष्टता केंद्रे','Get in Touch':'संपर्क करा','Get In Touch':'संपर्क करा','Women & Children':'महिला व बाल आरोग्य','Emergency & Trauma':'आपत्कालीन व ट्रॉमा','Google Reviews':'Google पुनरावलोकने',
  'Patient-Centered Care':'रुग्णकेंद्रित सेवा','Compassion & Empathy':'करुणा व सहानुभूती','Medical Excellence & Innovation':'वैद्यकीय उत्कृष्टता व नवोपक्रम','Integrity & Ethics':'प्रामाणिकपणा व नैतिकता','Teamwork & Collaboration':'टीमवर्क व सहकार्य','Accessibility & Affordability':'सुलभता व परवडणारी सेवा',
  'Call':'कॉल','Appointment Request - Gawade Multispeciality Hospital':'अपॉइंटमेंट विनंती - गवाडे मल्टिस्पेशालिटी हॉस्पिटल',
  'Patient Name':'रुग्णाचे नाव','Mobile Number':'मोबाईल नंबर','Preferred Date':'पसंतीची तारीख','Preferred Time':'पसंतीची वेळ','Doctor / Department':'डॉक्टर / विभाग','Reason for Visit':'भेटीचे कारण','Submit':'सबमिट'
};
const i18nOriginals = new WeakMap();
function applyLanguage(lang){
  document.documentElement.lang = lang === 'mr' ? 'mr' : 'en';
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){const p=node.parentElement;if(!p||['SCRIPT','STYLE','NOSCRIPT'].includes(p.tagName)) return NodeFilter.FILTER_REJECT;return node.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;}});
  const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node=>{if(!i18nOriginals.has(node)) i18nOriginals.set(node,node.nodeValue); const original=i18nOriginals.get(node); const key=original.trim(); if(lang==='mr' && I18N_MR[key]){node.nodeValue=original.replace(key,I18N_MR[key]);}else{node.nodeValue=original;}});
  document.querySelectorAll('input,textarea').forEach(el=>{if(!el.dataset.enPlaceholder) el.dataset.enPlaceholder=el.placeholder||''; const key=el.dataset.enPlaceholder; el.placeholder=(lang==='mr'&&I18N_MR[key])?I18N_MR[key]:key;});
  const b=document.getElementById('langToggle'); if(b) b.textContent=lang==='mr'?'English':'मराठी';
  localStorage.setItem('gawadeLang',lang);
}
const langToggle=document.getElementById('langToggle'); if(langToggle){langToggle.addEventListener('click',()=>applyLanguage((localStorage.getItem('gawadeLang')||'en')==='en'?'mr':'en'));}
applyLanguage(localStorage.getItem('gawadeLang')||'en');
